name: Purchase and Add New .org Domain
description: Request to purchase and add a new .org domain to the Cloudflare account
title: '[DOMAIN PURCHASE REQUEST] {domain_name}'
labels: ['domain-purchase', 'cloudflare']
body:
  - type: markdown
    attributes:
      value: |
        If you have trouble creating the request, contact Clarke Moyer by text at 520-222-8104.
  - type: markdown
    attributes:
      value: |
        ## Domain Purchase Request
        Use this template to request the purchase and addition of a new .org domain to the FFC Cloudflare account.

        Note: Domains are free for all requestors. Budget approval is handled by FFC administrators; requestors do not need to confirm purchase approval.

  - type: input
    id: domain_name
    attributes:
      label: Domain Name
      description: Enter the exact domain name you want to purchase
      placeholder: 'example.org'
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Mandatory Settings
        The following are mandatory and applied per FFC policy:
        - [x] Website will be pointed to GitHub Pages automatically (per FFC policy)
        - [x] Microsoft 365 Email (Exchange Online DNS/MX)
        - [x] DMARC reporting (rua/ruf via Cloudflare with FFC-managed mailboxes)
        - [x] SPF (Microsoft 365 record)

        Website (GitHub Pages): Automatic pointing ensures consistent staging/site hosting with GitHub Pages.

        Microsoft 365 email: Required provider; configures DNS/MX for Exchange Online.

        DMARC: Configured and managed in Cloudflare using FFC-managed `rua/ruf` mailboxes; enforces alignment and helps prevent spoofing.

        SPF: Authorizes Exchange Online as a permitted sender; prevents softfail. (NOTE: Other senders require prior FFC approval.)

  - type: checkboxes
    id: mandatory_ack
    attributes:
      label: Mandatory Settings Acknowledgement
      description: Confirm all mandatory settings will be configured
      options:
        - label:
            I acknowledge these mandatory settings (GitHub Pages, Microsoft 365 Email, DMARC, SPF)
            will be configured
          required: true

  - type: checkboxes
    id: email_mta_sts
    attributes:
      label: MTA‑STS Policy (Optional)
      description: Publish `_mta-sts` DNS and host HTTPS policy file
      options:
        - label: MTA-STS policy (_mta-sts)
  - type: markdown
    attributes:
      value: |
        MTA‑STS policy (`_mta-sts`): Instructs senders to require TLS to your MX (Exchange Online), preventing downgrade/MITM.

  - type: checkboxes
    id: email_tlsrpt
    attributes:
      label: TLS Reporting (Optional)
      description: Publish `_smtp._tls` DNS for aggregate TLS failure reports
      options:
        - label: TLS Reporting (_smtp._tls)
  - type: markdown
    attributes:
      value: |
        TLS Reporting (`_smtp._tls`): Aggregated delivery telemetry for TLS failures; pairs with MTA‑STS to monitor encryption issues.

  - type: checkboxes
    id: email_dkim
    attributes:
      label: Additional DKIM Selectors (Optional)
      description: Configure extra DKIM selectors for specialized send streams
      options:
        - label: Additional DKIM selectors
  - type: markdown
    attributes:
      value: |
        Additional DKIM selectors: Separate signing keys per send stream; supported by Exchange Online (e.g., `selector1`/`selector2`).

  - type: checkboxes
    id: email_bimi
    attributes:
      label: BIMI (Optional)
      description: Publish BIMI TXT with logo URL and VMC (if applicable)
      options:
        - label: BIMI (brand logo + VMC)
  - type: markdown
    attributes:
      value: |
        BIMI (brand logo + VMC): Logo shown by providers that support BIMI; Microsoft 365 does not display BIMI in Outlook. Requires DMARC enforcement and compliant SVG logo; VMC often required.

  - type: checkboxes
    id: mandatory_uses
    attributes:
      label: Mandatory Uses
      description: All must be selected
      options:
        - label: Website (GitHub Pages only)
          required: true
        - label: Verification with Google tools (Analytics, PageSpeed, Search Console)
          required: true

  - type: checkboxes
    id: optional_uses
    attributes:
      label: Optional Uses
      description: Select if applicable
      options:
        - label: Newsletter service verification

  - type: checkboxes
    id: verification_tools
    attributes:
      label: Verification/Telemetry Tools (if applicable)
      description: Select tools requiring DNS verification or site checks
      options:
        - label: Google Analytics
        - label: Google Search Console
        - label: Google PageSpeed Insights
        - label: Microsoft Clarity

  - type: textarea
    id: project_details
    attributes:
      label: Project Details
      description: Provide details about the project or initiative this domain will support
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ICANN Registrant Contact (Required)
        Provide accurate registrant contact details required for domain registration (ICANN).

  - type: input
    id: registrant_name
    attributes:
      label: Registrant Name
      description: Legal name of the registrant (person or organization representative)
      placeholder: 'Jane Doe'
    validations:
      required: true

  - type: input
    id: registrant_org
    attributes:
      label: Registrant Organization
      description: Organization name (if applicable)
      placeholder: 'Free For Charity'
    validations:
      required: true

  - type: input
    id: registrant_email
    attributes:
      label: Registrant Email
      description: Primary contact email for the registrant
      placeholder: 'jane.doe@example.org'
    validations:
      required: true

  - type: input
    id: registrant_phone
    attributes:
      label: Registrant Phone
      description: Phone number including country code
      placeholder: '+1-555-555-1212'
    validations:
      required: true

  - type: input
    id: registrant_address1
    attributes:
      label: Registrant Address Line 1
      placeholder: '123 Main St'
    validations:
      required: true

  - type: input
    id: registrant_address2
    attributes:
      label: Registrant Address Line 2
      placeholder: 'Suite 200'
    validations:
      required: false

  - type: input
    id: registrant_city
    attributes:
      label: City
      placeholder: 'Tucson'
    validations:
      required: true

  - type: input
    id: registrant_state
    attributes:
      label: State/Province
      placeholder: 'AZ'
    validations:
      required: true

  - type: input
    id: registrant_postal_code
    attributes:
      label: Postal Code
      placeholder: '85701'
    validations:
      required: true

  - type: input
    id: registrant_country
    attributes:
      label: Country
      placeholder: 'US'
    validations:
      required: true

  - type: checkboxes
    id: icann_ack
    attributes:
      label: ICANN Accuracy Acknowledgment
      description:
        Confirm all registrant details are accurate and kept up to date per ICANN requirements
      options:
        - label: I confirm registrant information is accurate
          required: true

  - type: markdown
    attributes:
      value: |
        ### Administrative Contact (Optional)
        If different from registrant, provide admin contact.

  - type: input
    id: admin_name
    attributes:
      label: Admin Contact Name
    validations:
      required: false

  - type: input
    id: admin_email
    attributes:
      label: Admin Contact Email
    validations:
      required: false

  - type: input
    id: admin_phone
    attributes:
      label: Admin Contact Phone
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Technical Contact (Optional)
        If different from registrant, provide technical contact.

  - type: input
    id: tech_name
    attributes:
      label: Technical Contact Name
    validations:
      required: false

  - type: input
    id: tech_email
    attributes:
      label: Technical Contact Email
    validations:
      required: false

  - type: input
    id: tech_phone
    attributes:
      label: Technical Contact Phone
    validations:
      required: false

  - type: checkboxes
    id: dns_config
    attributes:
      label: DNS Configuration Needed
      description: Select all that apply
      options:
        - label: Point to GitHub Pages (apex domain)
        - label: Point to GitHub Pages (subdomain)
        - label: Custom DNS configuration (specify in Additional DNS Records below)
        - label: Standard FFC configuration

  - type: textarea
    id: additional_dns
    attributes:
      label: Additional DNS Records
      description: List any specific DNS records needed (A, CNAME, MX, TXT, etc.)
      placeholder: |
        Example:
        - A record: @ -> 203.0.113.42
        - CNAME: www -> example.org

  - type: markdown
    attributes:
      value: |
        ### Timeline
        FFC seeks to process domain name purchase requests within 1 week. If your request has not been assigned within 1 week, please text Clarke Moyer at 520-222-8104.

  - type: checkboxes
    id: post_purchase
    attributes:
      label: Post-Purchase Actions Required
      description: Check all that apply
      options:
        - label: Configure nameservers to Cloudflare
        - label: Set up DNS records
        - label: Configure SSL/TLS settings
        - label: Enable DNSSEC

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other relevant information

  - type: markdown
    attributes:
      value: |
        ---
        ## For Administrator Use

        ### Pre-Purchase Checklist
        - [ ] Domain availability confirmed
        - [ ] Budget approved (FFC admin only)
        - [ ] Domain aligns with FFC mission and policies
        - [ ] No trademark or legal concerns

        ### Purchase Steps
        1. [ ] Purchase domain from registrar (e.g., Namecheap, Google Domains)
        2. [ ] Add domain to Cloudflare account
        3. [ ] Update nameservers at registrar to Cloudflare's nameservers
        4. [ ] Configure DNS records as requested
        5. [ ] Enable security settings (SSL/TLS, DNSSEC)
        6. [ ] Verify domain is working correctly
        7. [ ] Document domain in inventory

        ### Verification
        - [ ] Domain added to Cloudflare
        - [ ] DNS records configured
        - [ ] SSL/TLS working
        - [ ] Domain resolves correctly
