name: Purchase and Add New .org Domain
description: Request to purchase and add a new .org domain to the Cloudflare account
title: "[DOMAIN PURCHASE] {domain_name}"
labels: ["domain-purchase", "cloudflare"]
body:
  - type: markdown
    attributes:
      value: |
        If you have trouble creating the issue, contact Clarke Moyer by text at 520-222-8104.
  - type: markdown
    attributes:
      value: |
        ## Domain Purchase Request
        Use this template to request the purchase and addition of a new .org domain to the FFC Cloudflare account.
        
        Note: Domains are free for all requestors. Budget approval is handled by FFC administrators; requestors do not need to confirm purchase approval.

  - type: input
    id: domain_name
    attributes:
      label: Domain Name
      description: Enter the exact domain name you want to purchase
      placeholder: "example.org"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: Purpose
      description: Describe the purpose of this domain and how it will be used
      placeholder: "This domain will be used for..."
    validations:
      required: true

  - type: textarea
    id: project_details
    attributes:
      label: Project Details
      description: Provide details about the project or initiative this domain will support
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## ICANN Registrant Contact (Required)
        Provide accurate registrant contact details required for domain registration (ICANN).

  - type: input
    id: registrant_name
    attributes:
      label: Registrant Name
      description: Legal name of the registrant (person or organization representative)
      placeholder: "Jane Doe"
    validations:
      required: true

  - type: input
    id: registrant_org
    attributes:
      label: Registrant Organization
      description: Organization name (if applicable)
      placeholder: "Free For Charity"
    validations:
      required: true

  - type: input
    id: registrant_email
    attributes:
      label: Registrant Email
      description: Primary contact email for the registrant
      placeholder: "jane.doe@example.org"
    validations:
      required: true

  - type: input
    id: registrant_phone
    attributes:
      label: Registrant Phone
      description: Phone number including country code
      placeholder: "+1-555-555-1212"
    validations:
      required: true

  - type: input
    id: registrant_address1
    attributes:
      label: Registrant Address Line 1
      placeholder: "123 Main St"
    validations:
      required: true

  - type: input
    id: registrant_address2
    attributes:
      label: Registrant Address Line 2
      placeholder: "Suite 200"
    validations:
      required: false

  - type: input
    id: registrant_city
    attributes:
      label: City
      placeholder: "Tucson"
    validations:
      required: true

  - type: input
    id: registrant_state
    attributes:
      label: State/Province
      placeholder: "AZ"
    validations:
      required: true

  - type: input
    id: registrant_postal_code
    attributes:
      label: Postal Code
      placeholder: "85701"
    validations:
      required: true

  - type: input
    id: registrant_country
    attributes:
      label: Country
      placeholder: "US"
    validations:
      required: true

  - type: checkboxes
    id: icann_ack
    attributes:
      label: ICANN Accuracy Acknowledgment
      description: Confirm all registrant details are accurate and kept up to date per ICANN requirements
      options:
        - label: I confirm registrant information is accurate
          required: true

  - type: markdown
    attributes:
      value: |
        ### Administrative Contact (Optional)
        If different from registrant, provide admin contact.

  - type: input
    id: admin_name
    attributes:
      label: Admin Contact Name
    validations:
      required: false

  - type: input
    id: admin_email
    attributes:
      label: Admin Contact Email
    validations:
      required: false

  - type: input
    id: admin_phone
    attributes:
      label: Admin Contact Phone
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ### Technical Contact (Optional)
        If different from registrant, provide technical contact.

  - type: input
    id: tech_name
    attributes:
      label: Technical Contact Name
    validations:
      required: false

  - type: input
    id: tech_email
    attributes:
      label: Technical Contact Email
    validations:
      required: false

  - type: input
    id: tech_phone
    attributes:
      label: Technical Contact Phone
    validations:
      required: false

  - type: checkboxes
    id: dns_config
    attributes:
      label: DNS Configuration Needed
      description: Select all that apply
      options:
        - label: Point to GitHub Pages (apex domain)
        - label: Point to GitHub Pages (subdomain)
        - label: Custom DNS configuration (specify in Additional DNS Records below)
        - label: Standard FFC configuration

  - type: textarea
    id: additional_dns
    attributes:
      label: Additional DNS Records
      description: List any specific DNS records needed (A, CNAME, MX, TXT, etc.)
      placeholder: |
        Example:
        - A record: @ -> 203.0.113.42
        - CNAME: www -> example.org


  - type: input
    id: timeline
    attributes:
      label: Timeline
      description: When is this domain needed?
      placeholder: "ASAP or specific date"
    validations:
      required: true

  - type: checkboxes
    id: post_purchase
    attributes:
      label: Post-Purchase Actions Required
      description: Check all that apply
      options:
        - label: Configure nameservers to Cloudflare
        - label: Set up DNS records
        - label: Configure SSL/TLS settings
        - label: Enable DNSSEC

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any other relevant information

  - type: markdown
    attributes:
      value: |
        ---
        ## For Administrator Use
        
        ### Pre-Purchase Checklist
        - [ ] Domain availability confirmed
        - [ ] Budget approved (FFC admin only)
        - [ ] Domain aligns with FFC mission and policies
        - [ ] No trademark or legal concerns
        
        ### Purchase Steps
        1. [ ] Purchase domain from registrar (e.g., Namecheap, Google Domains)
        2. [ ] Add domain to Cloudflare account
        3. [ ] Update nameservers at registrar to Cloudflare's nameservers
        4. [ ] Configure DNS records as requested
        5. [ ] Enable security settings (SSL/TLS, DNSSEC)
        6. [ ] Verify domain is working correctly
        7. [ ] Document domain in inventory
        
        ### Verification
        - [ ] Domain added to Cloudflare
        - [ ] DNS records configured
        - [ ] SSL/TLS working
        - [ ] Domain resolves correctly
