---
name: Purchase and Add New .org Domain
about: Request to purchase and add a new .org domain to the Cloudflare account
title: '[DOMAIN PURCHASE] '
labels: ['domain-purchase', 'cloudflare']
assignees: []

---

## Domain Purchase Request

### Domain Name
<!-- Please provide the exact domain name you want to purchase -->
**Domain**: [your-domain.org]

### Purpose
<!-- Describe the purpose of this domain and how it will be used -->


### Project Details
<!-- Provide details about the project or initiative this domain will support -->


### Technical Requirements

#### DNS Configuration Needed
<!-- Select all that apply -->
- [ ] Point to GitHub Pages (apex domain)
- [ ] Point to GitHub Pages (subdomain)
- [ ] Custom DNS configuration (specify below)
- [ ] Standard FFC configuration

#### Additional DNS Records
<!-- List any specific DNS records needed (A, CNAME, MX, TXT, etc.) -->


### Budget and Authorization
<!-- Confirm authorization for domain purchase -->
- [ ] I confirm this purchase has been approved
- **Estimated Annual Cost**: ~$15/year for .org domain

### Timeline
**Needed by**: [Date or "ASAP"]

### Post-Purchase Actions Required
<!-- Check all that apply -->
- [ ] Configure nameservers to Cloudflare
- [ ] Set up DNS records
- [ ] Configure SSL/TLS settings
- [ ] Enable DNSSEC
- [ ] Other (specify below)

### Additional Notes
<!-- Any other relevant information -->


---

## For Administrator Use

### Pre-Purchase Checklist
- [ ] Domain availability confirmed
- [ ] Budget approved
- [ ] Domain aligns with FFC mission and policies
- [ ] No trademark or legal concerns

### Purchase Steps
1. [ ] Purchase domain from registrar (e.g., Namecheap, Google Domains)
2. [ ] Add domain to Cloudflare account
3. [ ] Update nameservers at registrar to Cloudflare's nameservers
4. [ ] Configure DNS records as requested
5. [ ] Enable security settings (SSL/TLS, DNSSEC)
6. [ ] Verify domain is working correctly
7. [ ] Document domain in inventory

### Cloudflare API Commands
<!-- Will be executed by administrator using scripts in this repository -->
```bash
# Add domain to Cloudflare account
# This is typically done via Cloudflare Dashboard first

# Then configure DNS records using update_dns.py or custom scripts
python update_dns.py --name [domain-name] --type A --ip [IP-ADDRESS]
```

### Verification
- [ ] Domain added to Cloudflare
- [ ] DNS records configured
- [ ] SSL/TLS working
- [ ] Domain resolves correctly

### Completion Notes
<!-- Administrator notes on completion -->

