name: 02. Request New Website (Primary)
description: |
  Primary workflow: build a new charity website repo from the FFC template.
  Assignment triggers automation.
title: '[WEBSITE REQUEST]'
labels: ['website-request', 'github-pages', 'cloudflare']
body:
  - type: markdown
    attributes:
      value: |
        If you have trouble creating the request, contact Clarke Moyer by text at 520-222-8104.

  - type: markdown
    attributes:
      value: |
        ## New Website Request (Primary)

        This form is temporarily minimal while we resolve a GitHub UI issue.
        After you submit this issue, an administrator will assign it.

  - type: input
    id: domain
    attributes:
      label: Website Domain (no http://)
      description: |
        The apex/root domain name (example: `example.org`).
        Do not include `https://` and do not use `www`.
      placeholder: example.org
    validations:
      required: true

  - type: input
    id: technical_poc_github
    attributes:
      label: Technical POC GitHub Username
      description: |
        GitHub username for the charity technical point-of-contact.
        Example: `octocat`
      placeholder: octocat
    validations:
      required: true

  - type: dropdown
    id: website_situation
    attributes:
      label: Website Situation
      description: |
        Pick the closest match.

        This helps us understand what content already exists today, and what we may need to migrate later.
      options:
        - 'New charity domain name and new charity website'
        - 'New charity domain name but existing charity site (Wix / Squarespace / etc)'
        - 'Existing domain name and existing website (WordPress / formal hosting)'
    validations:
      required: true

  - type: input
    id: current_website
    attributes:
      label: Current Website URL (if any)
      description: |
        If you already have a website, paste the full URL so we can reference/scrape content later.

        Examples:
        - `https://example.org/`
        - `https://www.example.org/`

        If you do not have a current website, enter `N/A`.
      placeholder: https://example.org/
    validations:
      required: true

  - type: input
    id: org_name
    attributes:
      label: Organization Name (as displayed)
      description: Public display name for the website.
      placeholder: Example Charity
    validations:
      required: true

  - type: input
    id: footer_email
    attributes:
      label: Footer Contact Email
      description: Public email address to show in the site footer (for visitors to contact you).
      placeholder: info@example.org
    validations:
      required: true

  - type: input
    id: footer_phone
    attributes:
      label: Footer Contact Phone
      description: |
        Public phone number to show in the site footer. If you do not want a phone number displayed,
        enter `N/A`.
      placeholder: +1 (555) 555-1212
    validations:
      required: true

  - type: textarea
    id: leadership_lines
    attributes:
      label: Board / Leadership (optional for now)
      description: |
        One leader per line. Format: Name | Role/Title | LinkedIn URL
      placeholder: |
        Jane Doe | President | https://www.linkedin.com/in/janedoe
        John Smith | Treasurer | N/A
    validations:
      required: false

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any extra context or links.
      placeholder: |
        Current website (if any): https://example.org/
        Anything else we should know.
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **For admins:** assignment of this issue triggers the provisioning workflow.
