name: 02. Request New Website (Primary)
description: |
  Primary workflow: build a new charity website repo from the FFC template.
  Assignment triggers automation.
title: '[WEBSITE REQUEST]'
labels: ['website-request', 'github-pages', 'cloudflare']
body:
  - type: markdown
    attributes:
      value: |
        If you have trouble creating the request, contact Clarke Moyer by text at 520-222-8104.

  - type: markdown
    attributes:
      value: |
        ## New Website Request (Primary)

        After you submit this issue, an administrator will assign it.
        Assignment triggers automation.

        **Issue title requirement (IMPORTANT):**
        - Keep the prefix exactly as-is: `[WEBSITE REQUEST]`
        - Append the apex domain (no `https://`, no `www`)

        Examples:
        - ✅ `[WEBSITE REQUEST] freeforcharity.org`
        - ❌ `[WEBSITE REQUEST] https://freeforcharity.org`
        - ❌ `[WEBSITE REQUEST] www.freeforcharity.org`
        - ❌ `Website request for freeforcharity.org` (missing required prefix)

        Please read carefully before filling this out:
        - Do not enter `N/A` in any field.
        - We use automation + volunteers. Support is **best effort**.
        - Primary hosting is **GitHub Pages** (static site).
        - We only support US charities; address is displayed and must map.

  - type: markdown
    attributes:
      value: |
        ## Attestations (Required)
        These acknowledgements are required for Free For Charity provisioning.

        FreeForCharity.org policies (live):
        - Donation Policy: https://freeforcharity.org/free-for-charity-donation-policy/
        - Privacy Policy: https://freeforcharity.org/privacy-policy/
        - Terms of Service: https://freeforcharity.org/free-for-charity-terms-of-service/
        - Vulnerability Disclosure Policy: https://freeforcharity.org/vulnerability-disclosure-policy/
        - Security Acknowledgements: https://freeforcharity.org/security-acknowledgements

        Automation references (GitHub repo):
        - Contribution / automation process: https://github.com/FreeForCharity/FFC-Cloudflare-Automation/blob/main/CONTRIBUTING.md
        - Standard workflow expectations: https://github.com/FreeForCharity/FFC-Cloudflare-Automation/blob/main/docs/enforce-standard-workflow.md

  - type: checkboxes
    id: attest_nonprofit
    attributes:
      label: Nonprofit / charitable use
      description: Required
      options:
        - label: I attest this website and its content are for charitable/nonprofit purposes.
          required: true

  - type: checkboxes
    id: attest_policies
    attributes:
      label: Policies read
      description: Required
      options:
        - label: I have read the linked FreeForCharity.org policies and agree to follow them.
          required: true

  - type: checkboxes
    id: attest_support
    attributes:
      label: Support expectations
      description: Required
      options:
        - label:
            I understand support is best effort and provided by volunteers (no guaranteed
            timelines).
          required: true

  - type: markdown
    attributes:
      value: |
        ## Key Limitations (FYI)
        - **Hosting**: GitHub Pages (static). No server-side apps or databases in this workflow.
        - **DNS**: This workflow can create the repo even if DNS is not yet controlled by FFC Cloudflare.
        - **Address**: Displayed in the footer and used for map links. Must be a real US mailing address.
        - **Links**: Footer social links must use **https://**.

  - type: input
    id: domain
    attributes:
      label: Website Domain (no http://)
      description: |
        The apex/root domain name (example: `freeforcharity.org`).
        Do not include `https://` and do not use `www`.

        Examples:
        - ✅ `freeforcharity.org`
        - ❌ `https://freeforcharity.org`
        - ❌ `www.freeforcharity.org`
      placeholder: freeforcharity.org
    validations:
      required: true

  - type: input
    id: technical_poc_github
    attributes:
      label: Technical POC GitHub Username
      description: |
        GitHub username for the charity technical point-of-contact.
        This person will be added as a maintainer of the provisioned repo.

        Example: `FreeForCharity`
      placeholder: FreeForCharity
    validations:
      required: true

  - type: dropdown
    id: website_situation
    attributes:
      label: Website Situation
      description: |
        Pick the closest match.

        This helps us understand what content already exists today, and what we may need to migrate later.
      options:
        - 'New charity domain name and new charity website'
        - 'New charity domain name but existing charity site (Wix / Squarespace / etc)'
        - 'Existing domain name and existing website (WordPress / formal hosting)'
    validations:
      required: true

  - type: input
    id: current_website
    attributes:
      label: Current Website URL (if any)
      description: |
        If you already have a website, paste the full URL so we can reference/scrape content later.

        Examples:
        - `https://freeforcharity.org/`
        - `https://www.freeforcharity.org/`

        If you do not have a current website, leave this blank.
      placeholder: https://freeforcharity.org/
    validations:
      required: false

  - type: input
    id: org_name
    attributes:
      label: Organization Name (as displayed)
      description: Public display name for the website (how visitors will see it).
      placeholder: Free For Charity
    validations:
      required: true

  - type: input
    id: footer_email
    attributes:
      label: Footer Contact Email
      description: Public email address to show in the site footer (for visitors to contact you).
      placeholder: clarkemoyer@freeforcharity.org
    validations:
      required: true

  - type: input
    id: footer_phone
    attributes:
      label: Footer Contact Phone
      description: |
        Public US phone number to show in the site footer.
        Must be a valid US number (10 digits, or 11 digits starting with 1).
      placeholder: (520) 222-8104
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Footer Mailing Address
        This address is displayed in the footer.

        We require an address that maps to a real location.
        At minimum, you must provide a real **City**, **State**, and **ZIP code**.
        We only support US charities; **Country is hard-coded to United States**.

  - type: input
    id: address_line1
    attributes:
      label: Footer Mailing Address Line 1
      description: Street address or PO Box. Include suite/unit here if applicable.
      placeholder: 4030 Wake Forrest Road Suite 349
    validations:
      required: true

  - type: input
    id: address_city
    attributes:
      label: Footer Mailing City
      description: City for the footer address.
      placeholder: Raleigh
    validations:
      required: true

  - type: input
    id: address_state
    attributes:
      label: Footer Mailing State/Province
      description: State or province for the footer address.
      placeholder: NC (2-letter)
    validations:
      required: true

  - type: input
    id: address_postal
    attributes:
      label: Footer Mailing Postal Code
      description: US ZIP code (e.g., 85001 or 85001-1234).
      placeholder: '27609'
    validations:
      required: true

  - type: input
    id: ein
    attributes:
      label: EIN / Tax ID
      description: |
        EIN/Tax ID to display in the footer.
      placeholder: 46-2471893
    validations:
      required: true

  - type: textarea
    id: leadership_lines
    attributes:
      label: Board / Leadership
      description: |
        One leader per line. Format: Name | Role/Title | LinkedIn URL
        If you include a LinkedIn URL, it must start with https://
      placeholder: |
        Clarke Moyer | Executive Director | https://www.linkedin.com/company/freeforcharity/
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Social Links
        These URLs are used for the social icons in the footer.

  - type: input
    id: social_facebook
    attributes:
      label: Facebook URL
      description: Full URL (must start with https://).
      placeholder: https://www.facebook.com/freeforcharity
    validations:
      required: true

  - type: input
    id: social_x
    attributes:
      label: X / Twitter URL
      description: Full URL (must start with https://).
      placeholder: https://twitter.com/freeforcharity1
    validations:
      required: true

  - type: input
    id: social_linkedin
    attributes:
      label: LinkedIn URL
      description: Full URL (must start with https://).
      placeholder: https://www.linkedin.com/company/freeforcharity/
    validations:
      required: true

  - type: input
    id: social_github
    attributes:
      label: GitHub URL
      description: Full URL (must start with https://).
      placeholder: https://github.com/FreeForCharity
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        **For admins:** assignment of this issue triggers the provisioning workflow.
