name: Configure Apex Domain for GitHub Pages
description: Point an apex/root domain (e.g., example.org) to GitHub Pages
title: "[GITHUB PAGES APEX] "
labels: ["github-pages", "dns-config", "cloudflare"]
body:
  - type: markdown
    attributes:
      value: |
        ## GitHub Pages Apex Domain Configuration
        Use this template to configure an apex/root domain to point to GitHub Pages.
        
        **Apex domains** are root domains without subdomains (e.g., example.org, not www.example.org).

  - type: input
    id: apex_domain
    attributes:
      label: Apex Domain
      description: Enter the apex/root domain name
      placeholder: "example.org"
    validations:
      required: true

  - type: input
    id: github_org
    attributes:
      label: GitHub Organization/User
      description: GitHub organization or username
      placeholder: "FreeForCharity"
    validations:
      required: true

  - type: input
    id: repository_name
    attributes:
      label: Repository Name
      description: Name of the GitHub repository
      placeholder: "ffc-website"
    validations:
      required: true

  - type: input
    id: github_pages_url
    attributes:
      label: GitHub Pages URL
      description: Current GitHub Pages URL (before custom domain)
      placeholder: "freeforcharity.github.io or freeforcharity.github.io/repo-name"
    validations:
      required: true

  - type: dropdown
    id: repo_type
    attributes:
      label: Repository Type
      options:
        - Organization/User Pages (username.github.io)
        - Project Pages (username.github.io/project-name)
    validations:
      required: true

  - type: dropdown
    id: domain_status
    attributes:
      label: Current Domain Status in Cloudflare
      options:
        - Domain is already in Cloudflare account
        - Domain needs to be added to Cloudflare first (will create separate issue)
    validations:
      required: true

  - type: checkboxes
    id: dns_config
    attributes:
      label: DNS Configuration Requirements
      description: Standard GitHub Pages apex domain configuration
      options:
        - label: Create 4 A records pointing to GitHub Pages IP addresses
          required: true
        - label: Create www CNAME record (recommended)

  - type: checkboxes
    id: ssl_requirements
    attributes:
      label: SSL/TLS Requirements
      options:
        - label: Enable HTTPS
          required: true
        - label: Enforce HTTPS
          required: true

  - type: textarea
    id: additional_subdomains
    attributes:
      label: Additional Subdomains
      description: List any additional subdomains that need to be configured
      placeholder: |
        - www.example.org
        - blog.example.org

  - type: input
    id: timeline
    attributes:
      label: Timeline
      description: When is this configuration needed?
      placeholder: "ASAP or specific date"
    validations:
      required: true

  - type: textarea
    id: additional_notes
    attributes:
      label: Additional Notes
      description: Any special requirements or considerations

  - type: markdown
    attributes:
      value: |
        ---
        ## For Administrator Use
        
        ### Prerequisites
        - [ ] Domain is in Cloudflare account
        - [ ] GitHub repository exists and has content
        - [ ] GitHub Pages is enabled in repository settings
        
        ### GitHub Pages IP Addresses
        Current GitHub Pages IP addresses as of December 2025 (always verify at [GitHub Pages documentation](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain)):
        ```
        185.199.108.153
        185.199.109.153
        185.199.110.153
        185.199.111.153
        ```
        
        ⚠️ **Important**: Always verify these IPs are current before configuring DNS records.
        
        ### DNS Configuration (Cloudflare Dashboard)
        1. [ ] Login to Cloudflare Dashboard
        2. [ ] Navigate to DNS → Records
        3. [ ] Create 4 A records:
           - Type: A, Name: @, Content: 185.199.108.153, Proxy: Off (DNS only)
           - Type: A, Name: @, Content: 185.199.109.153, Proxy: Off (DNS only)
           - Type: A, Name: @, Content: 185.199.110.153, Proxy: Off (DNS only)
           - Type: A, Name: @, Content: 185.199.111.153, Proxy: Off (DNS only)
        4. [ ] Create www CNAME (if requested):
           - Type: CNAME, Name: www, Content: [username].github.io, Proxy: Off
        
        ### DNS Configuration (Python Script)
        ```bash
        export CLOUDFLARE_API_TOKEN="your-token-here"
        
        # Create A records for GitHub Pages (repeat for all 4 IPs)
        python update_dns.py --zone [domain.org] --name @ --type A --ip 185.199.108.153 --no-proxy
        python update_dns.py --zone [domain.org] --name @ --type A --ip 185.199.109.153 --no-proxy
        python update_dns.py --zone [domain.org] --name @ --type A --ip 185.199.110.153 --no-proxy
        python update_dns.py --zone [domain.org] --name @ --type A --ip 185.199.111.153 --no-proxy
        
        # Create www CNAME (optional)
        python update_dns.py --zone [domain.org] --name www --type CNAME --target [username].github.io --no-proxy
        ```
        
        ### GitHub Pages Configuration
        1. [ ] Navigate to repository Settings → Pages
        2. [ ] Under "Custom domain", enter the apex domain
        3. [ ] Click Save and wait for DNS check
        4. [ ] Once verified (green checkmark), enable "Enforce HTTPS"
        
        ### CNAME File
        ```bash
        # GitHub usually creates this automatically
        # If needed, create manually in repository root:
        echo "[domain.org]" > CNAME
        ```
        
        ### Verification
        ```bash
        # Check DNS propagation
        dig [domain.org] A +short
        dig www.[domain.org] CNAME +short
        
        # Test HTTPS
        curl -I https://[domain.org]
        ```
        
        ### Cloudflare Settings (Recommended)
        - [ ] SSL/TLS Mode: Full (not Full Strict)
        - [ ] Always Use HTTPS: On
        - [ ] Automatic HTTPS Rewrites: On
        - [ ] Minimum TLS Version: 1.2+
        - [ ] **Proxy Status: DNS Only (gray cloud)** ⚠️ Critical!
        
        ### Verification Checklist
        - [ ] All 4 A records created
        - [ ] www CNAME created (if requested)
        - [ ] Cloudflare proxy disabled (DNS only)
        - [ ] DNS propagation verified
        - [ ] Custom domain configured in GitHub Pages
        - [ ] DNS check passed (green checkmark)
        - [ ] CNAME file present in repository
        - [ ] HTTPS enabled and enforced
        - [ ] Website loads at https://[domain.org]
        - [ ] SSL certificate valid
        
        ### Timeline
        - DNS configuration: ~5 minutes
        - DNS propagation: 5-30 minutes
        - GitHub DNS verification: 10-30 minutes
        - SSL certificate: 1-24 hours
