name: 'DEPRECATED: Configure Apex Domain for GitHub Pages'
description: Deprecated. Use "Request New Website (Footer + Leadership)" for charity requests.
title: '[DEPRECATED GITHUB PAGES APEX] {apex_domain}'
labels: ['github-pages', 'dns-config', 'cloudflare']
body:
  - type: markdown
    attributes:
      value: |
        If you have trouble creating the issue, contact Clarke Moyer by text at 520-222-8104.
  - type: markdown
    attributes:
      value: |
        ## Deprecated
        This template asked requestors for admin/internal details.

        For new charity website requests, use:
        **Request New Website (Footer + Leadership)**

  - type: markdown
    attributes:
      value: |
        ## GitHub Pages Apex Domain Configuration
        Use this template to configure an apex/root domain to point to GitHub Pages.

        **Apex domains** are root domains without subdomains (e.g., example.org, not www.example.org).

  - type: input
    id: apex_domain
    attributes:
      label: Apex Domain
      description: Enter the apex/root domain name
      placeholder: 'example.org'
    validations:
      required: true

