name: 05. [ADMIN ONLY] Configure Apex Domain for GitHub Pages (Specialized)
description: |
  ADMIN ONLY. Specialized request: configure a root/apex domain to point to GitHub Pages.
title: '[GITHUB PAGES APEX] {apex_domain}'
labels: ['github-pages', 'dns-config', 'cloudflare']
body:
  - type: markdown
    attributes:
      value: |
        If you have trouble creating the issue, contact Clarke Moyer by text at 520-222-8104.
  - type: markdown
    attributes:
      value: |
        ## GitHub Pages Apex Domain Configuration
        Use this template to configure an apex/root domain to point to GitHub Pages.

        **Apex domains** are root domains without subdomains (e.g., example.org, not www.example.org).

  - type: input
    id: apex_domain
    attributes:
      label: Apex Domain
      description: |
        The root domain (no subdomain).

        Example: `example.org`
        Not: `https://example.org/`
        Not: `www.example.org`
      placeholder: example.org
    validations:
      required: true
