name: '98. Deprecated - Cloudflare Zone Add (removed)'

permissions:
  contents: read
  actions: read

on:
  workflow_dispatch:

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Deprecated workflow
        run: |
          echo "This legacy workflow required a separate zone-create token and has been removed."
          echo "Use the supported DNS workflows that authenticate with the cloudflare-prod environment secrets FFC_CLOUDFLARE_API_TOKEN_ZONE_AND_DNS and CM_CLOUDFLARE_API_TOKEN_ZONE_AND_DNS."
          exit 1
